version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pushnotifications
      - NODE_ENV=development
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_EMAIL=${VAPID_EMAIL}
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - yarn-cache:/usr/local/share/.cache/yarn

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  yarn-cache: